name: Branch static analysis, unit and ui tests check
on:
  pull_request:
    branches: [ main ]
jobs:
  static-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'corretto'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: ktlintCheck
        run: |
          chmod +x gradlew
          ./gradlew ktlintCheck

      - name: detekt
        run: |
          chmod +x gradlew
          ./gradlew detekt

      - name: lintDebug
        run: |
          chmod +x gradlew
          ./gradlew lintDebug

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build with Gradle
        run: |
          chmod +x gradlew
          ./gradlew assembleDebug assembleDebugAndroidTest

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: debug-apk
          path: |
            app/build/outputs/apk/debug/app-debug.apk
            app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk

  gradlew-unit-test:
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Run unit-tests with Gradle
        run: |
          chmod +x gradlew
          ./gradlew testDebugUnitTest 

      - name: Upload unit-test report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: unit-test-report
          path: app/build/reports/tests/testDebugUnitTest/

  gradlew-ui-test:
    needs: [ build ]
    strategy:
      matrix:
        shard: [ 0, 1, 2 ]
        api_level: [ 26, 29, 34 ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'

      - name: Download APK
        uses: actions/download-artifact@v4
        with:
          name: debug-apk
          path: apk

      - name: Run UI tests
        uses: ReactiveCircus/android-emulator-runner@v2

        with:
          api-level: ${{ matrix.api_level }}
          arch: x86_64
          profile: Nexus 6

          script: |
            adb install apk/debug/app-debug.apk
            adb install apk/androidTest/debug/app-debug-androidTest.apk
            adb shell am instrument -w -e numShards 3 -e shardIndex ${{ matrix.shard }} io.github.kobych.sanitly.test/androidx.test.runner.AndroidJUnitRunner

      - name: Upload UI test report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: ui-test-report-${{ matrix.shard }}
          path: app/build/reports/androidTests/connected/